# Generated by Django 2.0 on 2018-02-07 15:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('_erpp_authadmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='appmasteradmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ama_name', models.CharField(default=True, max_length=100)),
                ('ama_type', models.CharField(choices=[('ROT', 'ROOT'), ('MN', 'MENU'), ('FRM', 'FORM')], max_length=5)),
                ('ama_level', models.SmallIntegerField()),
                ('ama_isgroup', models.BooleanField(default=False)),
                ('ama_isactive', models.BooleanField(default=True)),
                ('ama_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('ama_creater', models.CharField(default=True, max_length=100)),
                ('ama_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('ama_updater', models.CharField(default=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='appmasteradminform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amaf_name', models.CharField(default=True, max_length=100)),
                ('amaf_filenamehtml', models.CharField(default=True, max_length=100)),
                ('amaf_isactive', models.BooleanField(default=True)),
                ('amaf_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('amaf_creater', models.CharField(default=True, max_length=100)),
                ('amaf_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('amaf_updater', models.CharField(default=True, max_length=100)),
                ('amaf_appmasteradmin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='_erpp_dasboardadmin.appmasteradmin')),
            ],
        ),
        migrations.CreateModel(
            name='appmasteradminpermissionform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amapf_isnew', models.BooleanField(default=True)),
                ('amapf_isselect', models.BooleanField(default=True)),
                ('amapf_isinsert', models.BooleanField(default=True)),
                ('amapf_isupdate', models.BooleanField(default=True)),
                ('amapf_isdelete', models.BooleanField(default=True)),
                ('amapf_isprint', models.BooleanField(default=True)),
                ('amapf_isexport', models.BooleanField(default=True)),
                ('amapf_isimport', models.BooleanField(default=True)),
                ('amapf_isactive', models.BooleanField(default=True)),
                ('amapf_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('amapf_creater', models.CharField(default=True, max_length=100)),
                ('amapf_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('amapf_updater', models.CharField(default=True, max_length=100)),
                ('amapf_appmasteradminform', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='_erpp_dasboardadmin.appmasteradminform')),
                ('amapf_useraccountadmin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='_erpp_authadmin.useraccountadmin')),
            ],
        ),
        migrations.CreateModel(
            name='appmasteradminstructure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amas_appmasteradmin_child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amas_appmasteradmin_child', to='_erpp_dasboardadmin.appmasteradmin')),
                ('amas_appmasteradmin_parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amas_appmasteradmin_parent', to='_erpp_dasboardadmin.appmasteradmin')),
            ],
        ),
    ]
