# Generated by Django 2.0 on 2018-02-07 15:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='useraccountadmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uaa_username', models.CharField(max_length=100, unique=True)),
                ('uaa_userpassword', models.CharField(default=True, max_length=100)),
                ('uaa_isactive', models.BooleanField(default=False)),
                ('uaa_keystone_id', models.IntegerField(default=True, null=True)),
                ('uaa_keystone_user_id', models.CharField(default=True, max_length=50, null=True)),
                ('uaa_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('uaa_creater', models.CharField(default=True, max_length=100)),
                ('uaa_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('uaa_updater', models.CharField(default=True, max_length=100)),
                ('uaa_issuspend', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='userfotoprofileadmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ufpa_name', models.CharField(default=True, max_length=100)),
                ('ufpa_status', models.CharField(default=True, max_length=100)),
                ('ufpa_note', models.CharField(default=True, max_length=100)),
                ('ufpa_path', models.CharField(default=True, max_length=100)),
                ('ufpa_filename', models.CharField(default=True, max_length=100)),
                ('ufpa_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('ufpa_creater', models.CharField(default=True, max_length=100)),
                ('ufpa_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('ufpa_updater', models.CharField(default=True, max_length=100)),
                ('ufpa_useraccountadmin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='_erpp_authadmin.useraccountadmin')),
            ],
        ),
        migrations.CreateModel(
            name='userprofileadmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upa_name', models.CharField(default=True, max_length=100)),
                ('upa_birthplace', models.CharField(default=True, max_length=100)),
                ('upa_birthdate', models.DateField()),
                ('upa_gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('upa_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('upa_creater', models.CharField(default=True, max_length=100)),
                ('upa_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('upa_updater', models.CharField(default=True, max_length=100)),
                ('upa_useraccountadmin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='_erpp_authadmin.useraccountadmin')),
            ],
        ),
        migrations.CreateModel(
            name='usertypeadmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uta_name', models.CharField(default=True, max_length=100, unique=True)),
                ('uta_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('uta_creater', models.CharField(default=True, max_length=100)),
                ('uta_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('uta_updater', models.CharField(default=True, max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='useraccountadmin',
            name='uaa_usertypeadmin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='_erpp_authadmin.usertypeadmin'),
        ),
    ]
